name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
      - run: docker build -t benjaminjm112/frontend -f Dockerfile.dev .
      - name: Run Tests
      - run: docker run --rm -e CI=true benjaminjm112/frontend npm run test 
